<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="CityHash">
      <HintPath>..\..\FMDL-Studio-v2\Assets\Fmdl Studio\References\CityHash.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\FMDL-Studio-v2\Assets\Fmdl Studio\fmdl_dictionary.txt">
      <Link>Resources\fmdl_dictionary.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\FMDL-Studio-v2\Assets\Fmdl Studio\qar_dictionary.txt">
      <Link>Resources\qar_dictionary.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
